export default function TermsOfServicePage() {
  return (
    <main className="min-h-screen bg-black text-white px-6 py-16">
      <div className="max-w-2xl mx-auto">
        <a href="/" className="text-sm text-gray-400 underline">
          ← Back
        </a>

        <h1 className="text-4xl font-bold mt-6">Terms of Service</h1>
        <p className="mt-2 text-gray-400 text-sm">Last updated: September 13, 2026</p>

        <div className="mt-10 space-y-8 text-gray-300 leading-relaxed">
          <section>
            <h2 className="text-xl font-semibold text-white">What this platform is</h2>
            <p className="mt-2">
              AIVA is an AI-powered customer support platform: it answers a business&apos;s customers over
              their website chat widget, Facebook Messenger, Instagram, and WhatsApp, hands off to a human
              when it can&apos;t help, and gives that business tools to manage conversations, orders,
              invoices, and their customer records. These terms cover use of the AIVA dashboard by a
              business and its staff (&quot;you&quot;).
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white">Accounts and access</h2>
            <ul className="mt-2 list-disc list-inside space-y-1">
              <li>You&apos;re responsible for keeping your login credentials confidential and for all activity under your account.</li>
              <li>A login is scoped to one business&apos;s dashboard; you agree not to attempt to access another business&apos;s data.</li>
              <li>We may disable a login that we reasonably believe is compromised, abused, or used to violate these terms.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white">Acceptable use</h2>
            <p className="mt-2">You agree not to use the platform to:</p>
            <ul className="mt-2 list-disc list-inside space-y-1">
              <li>Send unlawful, deceptive, or abusive content to customers.</li>
              <li>Attempt to disrupt, reverse-engineer, or gain unauthorized access to the platform or another business&apos;s data.</li>
              <li>Upload content you don&apos;t have the right to use, or that infringes someone else&apos;s rights.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white">AI-generated responses</h2>
            <p className="mt-2">
              Replies to your customers may be generated by third-party AI models. AI-generated answers can
              be wrong or incomplete — you&apos;re responsible for reviewing your AI Brain configuration and
              knowledge base, and for how your business relies on AI replies in place of a human. The
              platform includes a human handoff feature specifically so a person can step in when needed.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white">Your data and content</h2>
            <p className="mt-2">
              You retain ownership of the content you upload (knowledge base documents, product data,
              customer records) and of your conversation history. You grant us the right to process that
              content solely to operate the platform for you — generating replies, storing conversations,
              and providing the dashboard. See our{" "}
              <a href="/privacy" className="underline">
                Privacy Policy
              </a>{" "}
              for how customer message data is handled.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white">Subscriptions and billing</h2>
            <p className="mt-2">
              Paid access is billed on the plan and cycle shown in your Subscription panel. Fees are
              non-refundable except where required by law. We may suspend access for a business whose
              subscription has lapsed beyond any grace period shown in the dashboard.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white">Availability</h2>
            <p className="mt-2">
              We aim to keep the platform available and responsive but don&apos;t guarantee uninterrupted
              service — third-party AI providers, messaging platforms, or infrastructure can affect
              availability outside our control.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white">Termination</h2>
            <p className="mt-2">
              You may stop using the platform at any time. We may suspend or terminate access for a
              violation of these terms, non-payment, or misuse that puts other businesses or their customers
              at risk.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white">Changes to these terms</h2>
            <p className="mt-2">
              We may update these terms as the platform changes. Continued use after an update means you
              accept the revised terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white">Contact</h2>
            <p className="mt-2">
              Questions about these terms can be sent to{" "}
              <a href="mailto:optisuite10@gmail.com" className="underline">
                optisuite10@gmail.com
              </a>
              .
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
